version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_GPU_MEMORY=30g
      - OLLAMA_MAX_MEMORY=30g
    networks:
      - ollama-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-change-this
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_EMBEDDING_MODEL=kun432/cl-nagoya-ruri-large:latest
      - CUDA_VISIBLE_DEVICES=0
      - ENABLE_SIGNUP=true
    restart: always
    networks:
      - ollama-net

volumes:
  ollama_data:
  open-webui_data:

networks:
  ollama-net:
    external: true
